// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class NativeAppInfo {
  NativeAppInfo({
    required this.packageName,
    required this.label,
    required this.firstInstallMs,
  });

  String packageName;

  String label;

  /// PackageManager.firstInstallTime — 미사용 앱 정리의 기산점(§3 ④).
  /// 설치 직후라 사용 기록이 없는 앱이 "오래 안 쓴 앱"으로 오르는 것을 막는다.
  int firstInstallMs;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
      label,
      firstInstallMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAppInfo decode(Object result) {
    result as List<Object?>;
    return NativeAppInfo(
      packageName: result[0]! as String,
      label: result[1]! as String,
      firstInstallMs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAppInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packageName, other.packageName) && _deepEquals(label, other.label) && _deepEquals(firstInstallMs, other.firstInstallMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAppInfo(packageName: $packageName, label: $label, firstInstallMs: $firstInstallMs)';
  }
}

class MemInfo {
  MemInfo({
    required this.totalMemMb,
    required this.availMemMb,
    required this.appPssMb,
    required this.lowRamDevice,
  });

  int totalMemMb;

  int availMemMb;

  int appPssMb;

  bool lowRamDevice;

  List<Object?> _toList() {
    return <Object?>[
      totalMemMb,
      availMemMb,
      appPssMb,
      lowRamDevice,
    ];
  }

  Object encode() {
    return _toList();  }

  static MemInfo decode(Object result) {
    result as List<Object?>;
    return MemInfo(
      totalMemMb: result[0]! as int,
      availMemMb: result[1]! as int,
      appPssMb: result[2]! as int,
      lowRamDevice: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MemInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(totalMemMb, other.totalMemMb) && _deepEquals(availMemMb, other.availMemMb) && _deepEquals(appPssMb, other.appPssMb) && _deepEquals(lowRamDevice, other.lowRamDevice);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MemInfo(totalMemMb: $totalMemMb, availMemMb: $availMemMb, appPssMb: $appPssMb, lowRamDevice: $lowRamDevice)';
  }
}

class UsageSessionNative {
  UsageSessionNative({
    required this.packageName,
    required this.startMs,
    required this.endMs,
  });

  String packageName;

  int startMs;

  int endMs;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
      startMs,
      endMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static UsageSessionNative decode(Object result) {
    result as List<Object?>;
    return UsageSessionNative(
      packageName: result[0]! as String,
      startMs: result[1]! as int,
      endMs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UsageSessionNative || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packageName, other.packageName) && _deepEquals(startMs, other.startMs) && _deepEquals(endMs, other.endMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UsageSessionNative(packageName: $packageName, startMs: $startMs, endMs: $endMs)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeAppInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is MemInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is UsageSessionNative) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeAppInfo.decode(readValue(buffer)!);
      case 130:
        return MemInfo.decode(readValue(buffer)!);
      case 131:
        return UsageSessionNative.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// 설치 앱 조회·실행 — `<queries>` MAIN+LAUNCHER 범위(QUERY_ALL_PACKAGES 불사용).
class AppScanApi {
  /// Constructor for [AppScanApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppScanApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<NativeAppInfo>> getInstalledApps() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.AppScanApi.getInstalledApps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeAppInfo>();
  }

  Future<bool> launchApp(String packageName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.AppScanApi.launchApp$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 앱 아이콘 PNG 바이트 (기기 밖 전송 없음 — 런처 표시용, 없으면 null).
  Future<Uint8List?> getAppIcon(String packageName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.AppScanApi.getAppIcon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as Uint8List?;
  }
}

/// 메모리 통계 — RAM 게이팅·모델 로드 벤치용.
class DeviceStatsApi {
  /// Constructor for [DeviceStatsApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceStatsApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<MemInfo> getMemoryInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.DeviceStatsApi.getMemoryInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MemInfo;
  }

  /// 앱 데이터 파티션 가용 용량 — 모델 다운로드 사전 체크(§4.3, 3.6GB 기준).
  Future<int> getFreeStorageBytes() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.DeviceStatsApi.getFreeStorageBytes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// 활성 네트워크가 Wi-Fi인지 — 다운로드 동의 화면의 요금 경고용.
  Future<bool> isOnWifi() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.DeviceStatsApi.isOnWifi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Android 13+ 알림 권한 요청 — foreground 다운로드 진행률 알림(§4.3)과
  /// 화면 공유 상시 알림(50_ §7)이 이 권한 위에 선다. 결과 콜백 없음.
  /// **팝업을 띄울 수 없는 상태에서는 아무 일도 하지 않으므로**, 호출 전에
  /// [canRequestPostNotifications]로 묻고 불가면 호출부가 맥락에 맞는 대안을
  /// 정한다 — "알림 켜기"류 사용자 의도 경로는 설정 딥링크로, 모델 다운로드
  /// 같은 기회성 요청은 건너뛰기로(조용한 무반응 탭은 막다른 길이다, CG1).
  Future<void> requestPostNotifications() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.DeviceStatsApi.requestPostNotifications$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 지금 [requestPostNotifications]가 **시스템 팝업을 실제로 띄울 수 있는가.**
  /// Android 12 이하(런타임 권한 없음)·이미 허용됨·영구 거부(2회 거부)는 false.
  /// 영구 거부와 "아직 한 번도 안 물음"은 시스템이 구분해 주지 않으므로
  /// shouldShowRequestPermissionRationale + 요청 이력(영속 플래그)으로 가른다.
  Future<bool> canRequestPostNotifications() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.DeviceStatsApi.canRequestPostNotifications$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 알림 권한이 실제로 있는가. [requestPostNotifications]는 결과를 돌려주지 않고
  /// **2회 거부 뒤에는 호출해도 아무 일이 없으므로**, 상태를 따로 물어야 화면이
  /// "알림이 꺼져 있다"를 말해 줄 수 있다(50_ §7 가시성).
  /// Android 12 이하는 권한 자체가 없어 항상 true.
  Future<bool> isPostNotificationsGranted() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.DeviceStatsApi.isPostNotificationsGranted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}

/// 무권한 표준 인텐트(§4.1 intent_actions_api) — LLM이 아니라 여기(화이트리스트)가
/// 인텐트를 조립한다(§4.2). startActivity는 패키지 가시성 제한의 예외라
/// `<queries>` 추가 선언이 필요 없다. 실패(처리 앱 없음) 시 false.
class IntentActionsApi {
  /// Constructor for [IntentActionsApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IntentActionsApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 전화 걸기 화면(ACTION_DIAL — 즉시 발신 아님, 오발신 방지 §4.2).
  Future<bool> openDialer() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.IntentActionsApi.openDialer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 문자 작성 화면(ACTION_SENDTO smsto:).
  Future<bool> openSmsComposer() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.IntentActionsApi.openSmsComposer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 카메라(정지영상 모드).
  Future<bool> openCamera() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.IntentActionsApi.openCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 갤러리(CATEGORY_APP_GALLERY 기본 앱).
  Future<bool> openGallery() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.IntentActionsApi.openGallery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 알람 목록(ACTION_SHOW_ALARMS).
  Future<bool> showAlarms() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.IntentActionsApi.showAlarms$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 앱 삭제 안내(ACTION_DELETE) — 시스템 확인 다이얼로그 필수 경유, 우회 불가(§3 ④).
  Future<bool> requestUninstall(String packageName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.IntentActionsApi.requestUninstall$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packageName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 기기 잠금 설정 화면(ACTION_SECURITY_SETTINGS) — 잠금 미설정이면 보호자 등록
  /// 변경 보호(사전 A′)가 성립하지 않으므로, 막다른 길 대신 다음 행동을 준다.
  Future<bool> openSecuritySettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.IntentActionsApi.openSecuritySettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 이 앱의 알림 설정 화면(ACTION_APP_NOTIFICATION_SETTINGS). 알림 권한은 2회
  /// 거부하면 앱에서 다시 물을 수 없으므로, 그때 남는 유일한 경로다.
  Future<bool> openNotificationSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.IntentActionsApi.openNotificationSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}

/// 보호자 통화 코칭(v1.2 — docs/50_guardian_coaching.md) 네이티브 지원.
///
/// 화면 캡처 자체는 flutter_webrtc의 getDisplayMedia가 담당하고(OS 동의
/// 다이얼로그 포함), 여기서는 Android 14+가 요구하는 `mediaProjection`
/// foreground service 수명과 민감 화면 판정용 포그라운드 앱 조회만 맡는다.
class CoachingApi {
  /// Constructor for [CoachingApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CoachingApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 캡처 전에 FGS를 올린다. Android 14+는 이 서비스가 떠 있지 않으면
  /// MediaProjection 획득 자체가 실패한다. 공유 중 상시 알림도 이 서비스가 낸다.
  Future<bool> startShareService() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.CoachingApi.startShareService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> stopShareService() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.CoachingApi.stopShareService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 지금 화면 앞에 있는 앱 패키지명 — 민감 화면 3단 정책 판정용(§6).
  /// 사용정보 접근 권한이 없거나 알 수 없으면 빈 문자열.
  /// **감지 지연이 그대로 노출 시간이 되므로** 짧은 조회 창을 쓴다.
  Future<String> foregroundPackage() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.CoachingApi.foregroundPackage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }
}

/// 사용 패턴(§4.2 루틴) — UsageStatsManager queryEvents를 RESUMED/PAUSED 페어링으로
/// 세션화. PACKAGE_USAGE_STATS 특수 권한(설정 토글) 필요 — 없으면 축퇴 모드(§5).
class UsageStatsApi {
  /// Constructor for [UsageStatsApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UsageStatsApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> isUsageAccessGranted() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.UsageStatsApi.isUsageAccessGranted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 설정의 사용정보 접근 화면으로 딥링크(ACTION_USAGE_ACCESS_SETTINGS).
  Future<void> openUsageAccessSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.UsageStatsApi.openUsageAccessSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<UsageSessionNative>> queryUsageSessions(int startMs, int endMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.ongi.UsageStatsApi.queryUsageSessions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startMs, endMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<UsageSessionNative>();
  }
}
