// Autogenerated from Pigeon (v27.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package kr.tsp.ongi

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object OngiNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAppInfo (
  val packageName: String,
  val label: String,
  /**
   * PackageManager.firstInstallTime — 미사용 앱 정리의 기산점(§3 ④).
   * 설치 직후라 사용 기록이 없는 앱이 "오래 안 쓴 앱"으로 오르는 것을 막는다.
   */
  val firstInstallMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAppInfo {
      val packageName = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val firstInstallMs = pigeonVar_list[2] as Long
      return NativeAppInfo(packageName, label, firstInstallMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      label,
      firstInstallMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAppInfo
    return OngiNativePigeonUtils.deepEquals(this.packageName, other.packageName) && OngiNativePigeonUtils.deepEquals(this.label, other.label) && OngiNativePigeonUtils.deepEquals(this.firstInstallMs, other.firstInstallMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.packageName)
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.label)
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.firstInstallMs)
    return result
  }
  override fun toString(): String {
    return "NativeAppInfo(packageName=$packageName, label=$label, firstInstallMs=$firstInstallMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MemInfo (
  val totalMemMb: Long,
  val availMemMb: Long,
  val appPssMb: Long,
  val lowRamDevice: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MemInfo {
      val totalMemMb = pigeonVar_list[0] as Long
      val availMemMb = pigeonVar_list[1] as Long
      val appPssMb = pigeonVar_list[2] as Long
      val lowRamDevice = pigeonVar_list[3] as Boolean
      return MemInfo(totalMemMb, availMemMb, appPssMb, lowRamDevice)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalMemMb,
      availMemMb,
      appPssMb,
      lowRamDevice,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MemInfo
    return OngiNativePigeonUtils.deepEquals(this.totalMemMb, other.totalMemMb) && OngiNativePigeonUtils.deepEquals(this.availMemMb, other.availMemMb) && OngiNativePigeonUtils.deepEquals(this.appPssMb, other.appPssMb) && OngiNativePigeonUtils.deepEquals(this.lowRamDevice, other.lowRamDevice)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.totalMemMb)
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.availMemMb)
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.appPssMb)
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.lowRamDevice)
    return result
  }
  override fun toString(): String {
    return "MemInfo(totalMemMb=$totalMemMb, availMemMb=$availMemMb, appPssMb=$appPssMb, lowRamDevice=$lowRamDevice)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UsageSessionNative (
  val packageName: String,
  val startMs: Long,
  val endMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UsageSessionNative {
      val packageName = pigeonVar_list[0] as String
      val startMs = pigeonVar_list[1] as Long
      val endMs = pigeonVar_list[2] as Long
      return UsageSessionNative(packageName, startMs, endMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      startMs,
      endMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UsageSessionNative
    return OngiNativePigeonUtils.deepEquals(this.packageName, other.packageName) && OngiNativePigeonUtils.deepEquals(this.startMs, other.startMs) && OngiNativePigeonUtils.deepEquals(this.endMs, other.endMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.packageName)
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.startMs)
    result = 31 * result + OngiNativePigeonUtils.deepHash(this.endMs)
    return result
  }
  override fun toString(): String {
    return "UsageSessionNative(packageName=$packageName, startMs=$startMs, endMs=$endMs)"
  }
}
private open class OngiNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAppInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MemInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UsageSessionNative.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeAppInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is MemInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is UsageSessionNative -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 설치 앱 조회·실행 — `<queries>` MAIN+LAUNCHER 범위(QUERY_ALL_PACKAGES 불사용).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AppScanApi {
  fun getInstalledApps(): List<NativeAppInfo>
  fun launchApp(packageName: String): Boolean
  /** 앱 아이콘 PNG 바이트 (기기 밖 전송 없음 — 런처 표시용, 없으면 null). */
  fun getAppIcon(packageName: String): ByteArray?

  companion object {
    /** The codec used by AppScanApi. */
    val codec: MessageCodec<Any?> by lazy {
      OngiNativePigeonCodec()
    }
    /** Sets up an instance of `AppScanApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AppScanApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.AppScanApi.getInstalledApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getInstalledApps())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.AppScanApi.launchApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.launchApp(packageNameArg))
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.AppScanApi.getAppIcon$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getAppIcon(packageNameArg))
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * 메모리 통계 — RAM 게이팅·모델 로드 벤치용.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DeviceStatsApi {
  fun getMemoryInfo(): MemInfo
  /** 앱 데이터 파티션 가용 용량 — 모델 다운로드 사전 체크(§4.3, 3.6GB 기준). */
  fun getFreeStorageBytes(): Long
  /** 활성 네트워크가 Wi-Fi인지 — 다운로드 동의 화면의 요금 경고용. */
  fun isOnWifi(): Boolean
  /**
   * Android 13+ 알림 권한 요청 — foreground 다운로드 진행률 알림(§4.3)과
   * 화면 공유 상시 알림(50_ §7)이 이 권한 위에 선다. 결과 콜백 없음.
   * **팝업을 띄울 수 없는 상태에서는 아무 일도 하지 않으므로**, 호출 전에
   * [canRequestPostNotifications]로 묻고 불가면 호출부가 맥락에 맞는 대안을
   * 정한다 — "알림 켜기"류 사용자 의도 경로는 설정 딥링크로, 모델 다운로드
   * 같은 기회성 요청은 건너뛰기로(조용한 무반응 탭은 막다른 길이다, CG1).
   */
  fun requestPostNotifications()
  /**
   * 지금 [requestPostNotifications]가 **시스템 팝업을 실제로 띄울 수 있는가.**
   * Android 12 이하(런타임 권한 없음)·이미 허용됨·영구 거부(2회 거부)는 false.
   * 영구 거부와 "아직 한 번도 안 물음"은 시스템이 구분해 주지 않으므로
   * shouldShowRequestPermissionRationale + 요청 이력(영속 플래그)으로 가른다.
   */
  fun canRequestPostNotifications(): Boolean
  /**
   * 알림 권한이 실제로 있는가. [requestPostNotifications]는 결과를 돌려주지 않고
   * **2회 거부 뒤에는 호출해도 아무 일이 없으므로**, 상태를 따로 물어야 화면이
   * "알림이 꺼져 있다"를 말해 줄 수 있다(50_ §7 가시성).
   * Android 12 이하는 권한 자체가 없어 항상 true.
   */
  fun isPostNotificationsGranted(): Boolean

  companion object {
    /** The codec used by DeviceStatsApi. */
    val codec: MessageCodec<Any?> by lazy {
      OngiNativePigeonCodec()
    }
    /** Sets up an instance of `DeviceStatsApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceStatsApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.DeviceStatsApi.getMemoryInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getMemoryInfo())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.DeviceStatsApi.getFreeStorageBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getFreeStorageBytes())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.DeviceStatsApi.isOnWifi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isOnWifi())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.DeviceStatsApi.requestPostNotifications$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestPostNotifications()
              listOf(null)
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.DeviceStatsApi.canRequestPostNotifications$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.canRequestPostNotifications())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.DeviceStatsApi.isPostNotificationsGranted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isPostNotificationsGranted())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * 무권한 표준 인텐트(§4.1 intent_actions_api) — LLM이 아니라 여기(화이트리스트)가
 * 인텐트를 조립한다(§4.2). startActivity는 패키지 가시성 제한의 예외라
 * `<queries>` 추가 선언이 필요 없다. 실패(처리 앱 없음) 시 false.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface IntentActionsApi {
  /** 전화 걸기 화면(ACTION_DIAL — 즉시 발신 아님, 오발신 방지 §4.2). */
  fun openDialer(): Boolean
  /** 문자 작성 화면(ACTION_SENDTO smsto:). */
  fun openSmsComposer(): Boolean
  /** 카메라(정지영상 모드). */
  fun openCamera(): Boolean
  /** 갤러리(CATEGORY_APP_GALLERY 기본 앱). */
  fun openGallery(): Boolean
  /** 알람 목록(ACTION_SHOW_ALARMS). */
  fun showAlarms(): Boolean
  /** 앱 삭제 안내(ACTION_DELETE) — 시스템 확인 다이얼로그 필수 경유, 우회 불가(§3 ④). */
  fun requestUninstall(packageName: String): Boolean
  /**
   * 기기 잠금 설정 화면(ACTION_SECURITY_SETTINGS) — 잠금 미설정이면 보호자 등록
   * 변경 보호(사전 A′)가 성립하지 않으므로, 막다른 길 대신 다음 행동을 준다.
   */
  fun openSecuritySettings(): Boolean
  /**
   * 이 앱의 알림 설정 화면(ACTION_APP_NOTIFICATION_SETTINGS). 알림 권한은 2회
   * 거부하면 앱에서 다시 물을 수 없으므로, 그때 남는 유일한 경로다.
   */
  fun openNotificationSettings(): Boolean

  companion object {
    /** The codec used by IntentActionsApi. */
    val codec: MessageCodec<Any?> by lazy {
      OngiNativePigeonCodec()
    }
    /** Sets up an instance of `IntentActionsApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: IntentActionsApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.IntentActionsApi.openDialer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openDialer())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.IntentActionsApi.openSmsComposer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openSmsComposer())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.IntentActionsApi.openCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openCamera())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.IntentActionsApi.openGallery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openGallery())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.IntentActionsApi.showAlarms$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.showAlarms())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.IntentActionsApi.requestUninstall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.requestUninstall(packageNameArg))
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.IntentActionsApi.openSecuritySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openSecuritySettings())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.IntentActionsApi.openNotificationSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openNotificationSettings())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * 보호자 통화 코칭(v1.2 — docs/50_guardian_coaching.md) 네이티브 지원.
 *
 * 화면 캡처 자체는 flutter_webrtc의 getDisplayMedia가 담당하고(OS 동의
 * 다이얼로그 포함), 여기서는 Android 14+가 요구하는 `mediaProjection`
 * foreground service 수명과 민감 화면 판정용 포그라운드 앱 조회만 맡는다.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CoachingApi {
  /**
   * 캡처 전에 FGS를 올린다. Android 14+는 이 서비스가 떠 있지 않으면
   * MediaProjection 획득 자체가 실패한다. 공유 중 상시 알림도 이 서비스가 낸다.
   */
  fun startShareService(): Boolean
  fun stopShareService()
  /**
   * 지금 화면 앞에 있는 앱 패키지명 — 민감 화면 3단 정책 판정용(§6).
   * 사용정보 접근 권한이 없거나 알 수 없으면 빈 문자열.
   * **감지 지연이 그대로 노출 시간이 되므로** 짧은 조회 창을 쓴다.
   */
  fun foregroundPackage(): String

  companion object {
    /** The codec used by CoachingApi. */
    val codec: MessageCodec<Any?> by lazy {
      OngiNativePigeonCodec()
    }
    /** Sets up an instance of `CoachingApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CoachingApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.CoachingApi.startShareService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.startShareService())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.CoachingApi.stopShareService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopShareService()
              listOf(null)
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.CoachingApi.foregroundPackage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.foregroundPackage())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * 사용 패턴(§4.2 루틴) — UsageStatsManager queryEvents를 RESUMED/PAUSED 페어링으로
 * 세션화. PACKAGE_USAGE_STATS 특수 권한(설정 토글) 필요 — 없으면 축퇴 모드(§5).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface UsageStatsApi {
  fun isUsageAccessGranted(): Boolean
  /** 설정의 사용정보 접근 화면으로 딥링크(ACTION_USAGE_ACCESS_SETTINGS). */
  fun openUsageAccessSettings()
  fun queryUsageSessions(startMs: Long, endMs: Long): List<UsageSessionNative>

  companion object {
    /** The codec used by UsageStatsApi. */
    val codec: MessageCodec<Any?> by lazy {
      OngiNativePigeonCodec()
    }
    /** Sets up an instance of `UsageStatsApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UsageStatsApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.UsageStatsApi.isUsageAccessGranted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isUsageAccessGranted())
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.UsageStatsApi.openUsageAccessSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openUsageAccessSettings()
              listOf(null)
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.ongi.UsageStatsApi.queryUsageSessions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startMsArg = args[0] as Long
            val endMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.queryUsageSessions(startMsArg, endMsArg))
            } catch (exception: Throwable) {
              OngiNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
